### ISSUE TITLE
Request for clarification on minrx use cases

### ISSUE THREAD

**Issue by sebastiancarlos** [mikehaertel/minrx#3]
First of all, thank you for developing minrx and making it available as free software. After reading through the [GNU announcement](https://lists.gnu.org/archive/html/info-gnu/2024-07/msg00014.html) and this repo's README, I have a few questions to better understand its place in the ecosystem:

1. Could you elaborate on how minrx compares to other regex libraries in terms of features, performance goals, or design philosophy?

2. Is minrx intended to be a generally usable library for ERE matching that other software projects could adopt? If so, what advantages might it offer over existing solutions?

3. What specific problems or limitations in current GNU software does minrx aim to address? Is there a long-term vision for potentially standardizing ERE implementation across GNU programs by having them all use minrx?

I appreciate any insights you can provide to help clarify the project's goals and potential impact. Thank you for your time.

**Comment by mikehaertel** [comment]
1. The key feature of MinRX, that distinguishes it from almost all existing regex implementations, is that it computes the positions of the parenthesized subexpression matches exactly as specified in the POSIX standard.  For example, when matching the regexp `(foo|foobar)(bar)?baz` against the string `foobarbaz`, the POSIX-conforming result is that the first parenthesized subexpression must match `foobar` and the second parenthesized subexpression must not match anything.  In contrast, for example, the default regex library in typical Linux systems matches the first subexpression to `foo` and the second subexpression to `bar`, which is incorrect according to POSIX.  Nearly all existing matchers return the wrong subexpression matches in one case or another, whereas  MinRX strives to return results 100% in conformance with the standard.  These bugs in existing matchers are not easily fixed without substantially rewriting their code.  MinRX is written from scratch based on a new algorithm specifically tailored to solve the POSIX submatches problem correctly, while still allowing good performance.
2. Yes, other projects could benefit from adopting MinRX.  The advantages of MinRX are that it always finds the "leftmost-longest" overall match, and subexpression matches are computed recursively leftmost-longest exactly as documented in the POSIX standard.  Note that currently MinRX is still in early development and is not (yet) fast.  Depending on their requirements, would-be adopters might want to wait until MinRX performance has matured.
3. There is no single "long term vision .... across all GNU programs", because the GNU programs have many different developers with many different visions!  I hope to develop MinRX to a level of maturity and performance that will make it attractive for widespread use.
